### ISSUE TITLE
Pure Unicode solution for underline

### ISSUE THREAD

**Issue by alfsb** [sergev/x1-algol-compiler#2] opened 2024-07-30 15:17 UTC
U+0332 Combining Low Line somewhats simulates the backspace, underline of typewriters. It's not very perfect, as each glyph has a separate underline, but is way to represent every underlined glyph as originally typed on paper.

As alternative, exists U+035F Combining Double Macron Below, that can be used between letters.

Example of U+0332 on mono spaced font:
```
b̲e̲g̲i̲n̲
    r̲e̲a̲l̲ p̲r̲o̲c̲e̲d̲u̲r̲e̲ A(k, x1, x2, x3, x4, x5);
    v̲a̲l̲u̲e̲ k; i̲n̲t̲e̲g̲e̲r̲ k;
    r̲e̲a̲l̲ x1, x2, x3, x4, x5;
    b̲e̲g̲i̲n̲ 
        r̲e̲a̲l̲ p̲r̲o̲c̲e̲d̲u̲r̲e̲ B;
        b̲e̲g̲i̲n̲
            k:= k - 1;
            B:= A := A (k, B, x1, x2, x3, x4);
        e̲n̲d̲;
        A := i̲f k < 1 t̲h̲e̲n x4 + x5 e̲l̲s̲e B;
    e̲n̲d̲;
    print (A (10, 1.0, -1.0, -1.0, 1.0, 0.0));
e̲n̲d̲
```
Example of U+035F on mono spaced font:
```
b͟e͟g͟i͟n
    r͟e͟a͟l p͟r͟o͟c͟e͟d͟u͟r͟e A(k, x1, x2, x3, x4, x5);
    v͟a͟l͟u͟e k; i͟n͟t͟e͟g͟e͟r k;
    r͟e͟a͟l x1, x2, x3, x4, x5;
    b͟e͟g͟i͟n 
        r͟e͟a͟l p͟r͟o͟c͟e͟d͟u͟r͟e B;
        b͟e͟g͟i͟n
            k:= k - 1;
            B:= A := A (k, B, x1, x2, x3, x4);
        e͟n͟d;
        A := i͟f k < 1 t͟h͟e͟n x4 + x5 e͟l͟s͟e B;
    e͟n͟d;
    print (A (10, 1.0, -1.0, -1.0, 1.0, 0.0));
e͟n͟d
```
U+035F on proportional font:

b͟e͟g͟i͟n
&nbsp;&nbsp;&nbsp;&nbsp;r͟e͟a͟l p͟r͟o͟c͟e͟d͟u͟r͟e A(k, x1, x2, x3, x4, x5);
&nbsp;&nbsp;&nbsp;&nbsp;v͟a͟l͟u͟e k; i͟n͟t͟e͟g͟e͟r k;
&nbsp;&nbsp;&nbsp;&nbsp;r͟e͟a͟l x1, x2, x3, x4, x5;
&nbsp;&nbsp;&nbsp;&nbsp;b͟e͟g͟i͟n
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;r͟e͟a͟l p͟r͟o͟c͟e͟d͟u͟r͟e B;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;b͟e͟g͟i͟n
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;k:= k - 1;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;B:= A := A (k, B, x1, x2, x3, x4);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;e͟n͟d;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A := i͟f k < 1 t͟h͟e͟n x4 + x5 e͟l͟s͟e B;
&nbsp;&nbsp;&nbsp;&nbsp;e͟n͟d;
&nbsp;&nbsp;&nbsp;&nbsp;print (A (10, 1.0, -1.0, -1.0, 1.0, 0.0));
e͟n͟d

Original:
```
_b_e_g_i_n
    _r_e_a_l _p_r_o_c_e_d_u_r_e A(k, x1, x2, x3, x4, x5);
    _v_a_l_u_e k; _i_n_t_e_g_e_r k;
    _r_e_a_l x1, x2, x3, x4, x5;
    _b_e_g_i_n 
        _r_e_a_l _p_r_o_c_e_d_u_r_e B;
        _b_e_g_i_n
            k:= k - 1;
            B:= A := A (k, B, x1, x2, x3, x4);
        _e_n_d;
        A := _i_f k < 1 _t_h_e_n x4 + x5 _e_l_s_e B;
    _e_n_d;
    print (A (10, 1.0, -1.0, -1.0, 1.0, 0.0));
_e_n_d
```

**Comment by alfsb** [comment] 2024-07-30 15:29
Also, U+20D2 Combining Long Vertical Line Overlay can represent string delimitators: `A(<⃒XXXXX>⃒);` instead of `A(|<XXXXX|>);`.

But has way less font support. The above fails to show on my browser. On my text editor, underlines above fails, but vertical line works:

![image](https://github.com/user-attachments/assets/2b598f19-731c-4135-bcc5-760141887d0f)

**Comment by leobru** [comment] 2024-07-30 18:01
That is all very nice (and Chrome shows the combining long vertical line overlay properly), but what would be the actual issue?

**Comment by alfsb** [comment] 2024-07-30 19:05
Is more a suggestion. The files `man_or_boy.a60` and `appendix-b.a60` are hard do read with all extra `_`, and by using U+0332 and U+20D2, it would be possible to have faithfully source code reproductions that would be easier to read.

**Comment by sergev** [comment] 2024-07-30 19:51
Definitely it makes sense to enhance the `read_utf8_symbol()` routine to allow the proposed combinations. I would also add guillemets « and », as in JungleGenerator.

https://github.com/cwi-software-archive/Algol60/blob/main/JungleGenerator/JungleGenerator.pdf

**Comment by alfsb** [comment] 2024-07-30 23:50
I think I misread the repository organization, sorry.

I got here, from https://retrocomputing.stackexchange.com/questions/30427/how-were-strings-printed-in-the-dijkstra-zonneveld-algol-60-compiler-for-the-ele , and got stumped on `.a60` files from repository (pun intended).

If the objective is to both recreate old source and old compiler in modern times, maybe another code organization can make things easier. Instead of incrementing the compiler to accept keywords in various Unicode sequences, I now think it would be easier to make the current conversion tools as part of the compiler.

So it would be possible to have, for example, all Algol 60 source code formatted in "modern ASCII" (no underlines, `"` to delimit strings), and from these sources, use the conversion tools to generate and the compiler to use some derived files. Something like this.

* Algol 60 source as `.60` files. From this generate:
* One`file.t60`: an utf8 text file that recreates historical visual (with U+0332, etc);
* One `file.h60`: an HTML file that recreates historical visual (with CSS, Unicode);
* One `file.a60`: an historical bit correct, char aligned, text (tape?) source, in Electrologica X1 codification.

So it would be possible to have easy to edit source files (`.60`). that generate two easy to print/inspect versions (text and HTML, `.t60` and `.h60`), and also a faithful Algol 60 source file, in Electrologica X1 codification, so that the compiler can be also be faithful, by only accepting data as an Electrologica X1 would.

The compiler then would not worry about keywords in various forms. The "modern ASCII" to "Electrologica X1 coded" can be a pre-processor in the compiler, so the historical compiler can only see the Electrologica X1 coded data.

**Comment by leobru** [comment] 2024-07-31 05:19
Perhaps you're misunderstanding our priorities. At the moment, our goals are:

1. understanding the object code format the compiler generates; 
2. being able to feed it "library tapes" to satisfy the linker, as it appears that the (binary) library tapes had not survived;
3. simulating simple test programs, including I/O; at that point, additional conversion tools may become useful if we found ourselves spending an inordinate amount of time typing (already single-underscored, thanks to restrop.pl) keywords and strings quoted with `|<` and `|>`;
4. figuring out a way to augment the compiler to include the missing predefined procedure `XEEN`, used to read console switches, which is mentioned in the Kruseman Aretz document but absent in both the assembly language and the Pascal sources;
5. simulating [surviving Electrologica X1 Algol-60 programs](https://github.com/cwi-software-archive/Algol60/), starting from the one in the Appendix B of the  document.
...
N. Reproducing look-and-feel of the printouts.

Historical visuals would be nice if there is a TrueType or equivalent font reproducing all Friden Flexowriter characters for Algol, but I could not find one.  A high quality scan of the character set, if available, would be enough to generate the font using the "potrace" tool.

**Comment by sergev** [comment] 2024-07-31 17:59
The goal is to let people explore and enjoy the X1 Algol compiler. Direct utf8 input makes it prettier. There is not much pleasure in struggling with Flexowriter encoding. 😀 Same with extra underscores in keywords.

**Comment by gtoal** [comment] 2024-08-01 02:53
I'ld like to second the suggestion of having the compiler support Unicode input rather than (or possibly in addition to) flexowriter characters.  I have some utilities for handling this kind of encoding at https://github.com/gtoal/uparse  - it's primarily a generic parser project, but it includes a demo Algol 60 parser which reads most formats and outputs almost publication-syntax sources in Unicode, in the same style as the examples people have posted above.  There are quite a few Algol 60 source/test files in the tests/ subdirectory there, with canonicalised output in tests-html/* and tests-out/*
I've been interested in the X1 (and X8) compilers too - I have a page for them at https://gtoal.com/languages/algol60/x1algol/ and have worked on the X8 algol listings and corrected a few typos (I hope).
Another page you may find of interest: https://gtoal.com/languages/algol60/KDF9/ which has the algol sources of SOAP and related utilities.  I think my algol parser sources in the uparse project should all compile and run but if not let me know and I'll upload my working directory to my server - I've been working on a source to source language translator for another algol-like language so the generic parser has had a few updates and I've been waiting until the new translator is finished before I upload a consistent set of updated sources.
It's great to see this project you're working on and I'm looking forward to seeing it execute Algol code.  One thing to consider is rather than just an interpreter of the intermediate code, maybe take that intermediate code and effectively static binary translate it (to C) to generate directly executable binaries. (Not too tricky - I've written similar translators for real architectures in the 8 bit arcade gaming world so an architecture that was designed for interpretation should be even simpler to translate.)
PS If you don't feel it is appropriate to have the resurrected X1 compiler input Unicode directly, you can modify my parser to output Flexowriter (or plain ascii) versions instead and use it in a script as a filter for people who prefer that format.  Currently the -jff command-line option outputs code that is compatible with the 'jff' Algol 60 compiler, which seems to be the best of the ones currently available.

**Comment by leobru** [comment] 2024-08-01 08:36
@gtoal Thank you! We'll be using your compendium of Algol-60 programs to experiment with the X1 compiler in due time.
BTW, in your transcription of https://github.com/gtoal/uparse/blob/main/tests/quinio.a60 you've made [the same mistake](https://retrocomputing.stackexchange.com/a/30412/4025) as I have. In line 89, there must be the `≤ w` rather than `< w`. The upwards arrow in line 93 is correct, it is the exponentiation operator.

**Comment by gtoal** [comment] 2024-08-01 15:03
You're welcome.  Keep in touch (my email is gtoal@gtoal.com) - I'm happy to help out where I can, for instance I may have the odd utility that isn't already online so you're welcome to check with me before embarking on writing a utility from scratch just in case I already have code that may do some of what you need.
Thanks for the corrections, I've updated the github copy.  I've no doubt there will be other typos in some of the other files - I haven't _run_ many of the Algol programs, I was using them mainly to test the parser,  I think I have a few more test programs I've found that are not in that repository yet but it'll take a bit of effort to round them up and add them so probably not in the immediate future.  I do have some code I wrote to recreate text files from pdf's which I had to write, because cut & paste always loses the indentation.  It's not ready for a public release but if you find yourself needing it I can send you the work-in-progress. I've also been working on an OCR program specifically for converting fixed pitch line-printer listings which may be usable enough some day to recover old sources from scans that aren't also available as text files anywhere. (It's more accurate than the existing OCRs I've tried but _way_ slower and needs a lot of hand-holding, so again not ready for prime time...)

**Comment by alfsb** [comment] 2024-08-01 17:28
> Perhaps you're misunderstanding our priorities. At the moment, our goals are:

Yes, sorry. You can close this issue. A few late comments:

> 1. understanding the object code format the compiler generates;

(1) and (6) goes hand to hand. Thinking of end results, (1) may be about creating an "CPU manual" of Electrologica X1 and (6) may result in an Electrologica X1 simulator in C.

> 2. being able to feed it "library tapes" to satisfy the linker, as it appears that the (binary) library tapes had not survived;

The homepage of the MARST project cites the existence of ALGLIB, a library of Algol 60 standard procedures and other routines. The project itself is an Algol to C translation, so it may have functional variants of each of these tapes.

> 3. simulating simple test programs, including I/O; at that point, additional conversion tools may become useful if we found ourselves spending an inordinate amount of time typing (already single-underscored, thanks to restrop.pl) keywords and strings quoted with `|<` and `|>`;

The page https://ub.fnwi.uva.nl/computermuseum/X1flex.html (where I found about MARST) cites an alternative ASCII representation, and that MARST itself is capable from converting from and into tape format, Utf8, and his ASCII representation.

I suggest this project to name each one of these alternative representations, so it would be easier to identify each one. Say:

* `*.s60`: Stropped ASCII, where `_` and `|` only over strikes the next character;
* `*.m60`: MARST ASCII;
* `*.u60`: Unicode, that uses U+0332 and U+20D2 for combining over striking;
* `*.h60`: HTML, that uses CSS underline and Unicode combining;
* `*.f60`: Historical, bit correct, octet aligned, Friden Flexowriter tape code (need special font);
* `*.t60`: Historical, bit correct, octet aligned, Electrologica X1 tape code;

if `*.f60` and `*.t60` are the same, it would be possible to unify they into a `*.a60` file, with no ambiquity.

> Historical visuals would be nice if there is a TrueType or equivalent font reproducing all Friden Flexowriter characters for Algol, but I could not find one. A high quality scan of the character set, if available, would be enough to generate the font using the "potrace" tool.

HTML and Unicode are close enough, and Unicode has the advantage of being "correct" (as evidenced from the copy/paste problem of style underlined < and <=). Historical accurate would be very nice, but a low hanging fruit may be generating a modern Flexowriter charset from an existing font, by selecting whole matching glyphs, and generating missing glyphs by overstriking then in image format, and then ray tracing back with potrace-like tools.

**Comment by gtoal** [comment] 2024-08-01 19:07
> HTML and Unicode are close enough, and Unicode has the advantage of being "correct" (as evidenced from the copy/paste problem of style underlined < and <=). Historical accurate would be very nice, but a low hanging fruit may be generating a modern Flexowriter charset from an existing font, by selecting whole matching glyphs, and generating missing glyphs by overstriking then in image format, and then ray tracing back with potrace-like tools.

It's not the font, it's the encoding that's the issue.  I've been working in areas where this has to be handled, for quite a few years now, as my interest includes Atlas Autocode (and its later derivative, Imp) which was heavily influenced in its early days by the primary I/O device available being the Flexowriter.  I've looked at various different representations over the years and come to the conclusion that Unicode is getting close to being the best option.  It's not there yet because there are a small number of characters that are not fully supported - for example when viewing a text file on a console or in a text editor, not all characters are available, yet the same system will display them properly when viewing an HTML page containing them in a web browser.

Fortunately for Algol 60 there are very few of those problematic characters - the _10 exponent character that was (quite amazingly) added specifically for Algol 60 being one of them.  Any other representation that provides a flexowriter-compatible appearance relies on using HTML tricks and having HTML in source files turns out to be a major pain - basically it can no longer be considered a source file, but rather a marked-up document which has to be unmarked for use in a coding context.  The unmarking process is seldom as trivial as you might initially expect.

I have no objections to any scheme that is intended for producing listings of documents on web pages - heaven knows, I've done enough of them myself - but for files that are intended to be treated as input to a compiler or other source-aware utility (such as SOAP) there are only 3 options and of those only one is actually useful.  Those are:

a) Use the historical encoding for historical files.  Of course there were several paper tape encodings to chose from but essentially this is a good option for a history project but a terrible option for doing anything modern with those files.  This is actually the option our KDF9 history project chose, and I have to say there's probably only one person who actually uses it and that's the person who wrote the emulator.
b) Use whatever 7-bit ascii representation was used historically by users of the original system in installations where a flexowriter was not available.  I've seen a lot of old Algol 60 source code in these formats and not only is it as ugly as hell, the representations differed at every site that used them.  I'd avoid this option like the plague.
c) Use UTF-8 Unicode to represent the ideal canonical representation.  Note that even this (which is my preferred option now) is less than perfect - for example in Atlas Autocode up to 3 characters could be overstruck to create a visual representation of a single symbol - which may not have existed on *any* device but which was an ideal character to which the actual device would try to approximate as well as possible.  Unfortunately Unicode doesn't support arbitrary overstriking, or underlining of all characters.  In Atlas Autocode the exponent symbol was notionally a ↑ arrow but its representation on the Flexowriter was a vertical bar overstruck with the '*' multiplication symbol, which happened to be raised sufficiently that it sat at the top of the vertical bar.  My argument is that we would represent that character with ↑ in a Unicode text file rather than try to duplicate exactly the Flexowriter appearance - however I would do the latter in an HTML document such as a manual (such as https://gtoal.com/history.dcs.ed.ac.uk/archive/docs/atlasautocode.html )
Similarly the flexowriter would render >= as an underlined > but the ideal character was the ⩾ character - which is indeed available in Unicode.

So in my opinion, the best compromise is to store text files in Unicode, but render on web pages by processing the unicode into HTML, e.g. by removing the underlined letters and replacing with the &lt;u&gt; &lt;/u&gt; tags.  Note that this is actually an issue in Algol 60 as "go to" should underline the space but that is not supported by Unicode's underlining code.

These are some of the HTML tricks I've had to use to handle Flexowriter overstriking:

```
   <style type="text/css">
   a:link, a:visited { text-decoration: none }
   div.page {
   border-bottom: 1px solid #888888;
   padding-left: 1ex;}
   .vstrike{
   position: relative;
   }
   .vstrike::after{
   content: "\|";
   line-height: 100%;
   position: absolute;
   width: 100%;
   height: 100%;
   left: 0;
   top:0%;
   text-align: center;
   }
   .slstrike{
   position: relative;
   }
   .slstrike::after{
   content: "/";
   line-height: 100%;
   position: absolute;
   width: 100%;
   height: 100%;
   left: 0;
   top:0%;
   text-align: center;
   }
   </style>
```

(For those interested in diving deeper into the Algol encodings used in various compilers, have a look at the grammar file for my Algol 60 parser at https://github.com/gtoal/uparse/blob/main/algol60.g where I use many of the alternatives and comment the ones I couldn't use because of parsing ambiguities.)

**Comment by leobru** [comment] 2024-08-01 19:58
I'm closing the issue. The last comment, as the topic of overprinting came up:

Generalized overstriking in HTML, that I had to devise for Fortran, can be done by
&lt;pre style='line-height: 1.2; font-family: monospace, fixed, Courier;'>
and within it, a line to overlay the previous line is put into
&lt;div style='margin-top:-1.2em;margin-bottom:-1.2em'>

**Closed as not planned by leobru** 2024-08-01 19:58 UTC
